name: Update Sheets

on:
  schedule:
    - cron: "*/5 * * * *"
  workflow_dispatch:

jobs:
  run-script:
    runs-on: ubuntu-latest

    env:   # ✅ ADD THIS BLOCK
      GROQ_API_KEY: ${{ secrets.GROQ_API_KEY }}

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install huggingface_hub

      - name: Create service account json
        run: echo '${{ secrets.GOOGLE_CREDENTIALS }}' > service_account.json
      - name: Run ai script
        run: python consolidated.py
      - name: Run NSE script
        run: python nifty_move.py   # ✅ NOW WORKS

      - name: Run NSE script
       run: python NNSE.py

      - name: Run BSE script
        run: python BSE.py

      - name: Run et script
        run: python et.py

      - name: Run moneycontrol script
        run: python monc.py

      - name: Run words script
        run: python words.py

      - name: Run ai script
        run: python ai.py

