name: Update Sheets

on:
  schedule:
    - cron: "*/15 * * * *"
  workflow_dispatch:

jobs:
  run-script:
    runs-on: ubuntu-latest

    env:
      GROQ_API_KEY: ${{ secrets.GROQ_API_KEY }}
      HF_TOKEN: ${{ secrets.HF_TOKEN }}

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt
          pip install huggingface_hub

      - name: Create service account json
        run: echo '${{ secrets.GOOGLE_CREDENTIALS }}' > service_account.json

      # ======================================
      # UPDATE SOURCE SHEETS FIRST
      # ======================================

      - name: Run NSE script
        run: python NNSE.py

      - name: Run BSE script
        run: python BSE.py

      - name: Run ET script
        run: python et.py

      - name: Run Moneycontrol script
        run: python monc.py

      - name: Run Nifty Move script
        run: python nifty_move.py

      # # ======================================
      # # ANALYSIS SCRIPTS AFTER DATA UPDATE
      # # ======================================

      - name: Run Words script
        run: python words.py

      - name: Run AI script
        run: python ai.py

      - name: Run Consolidated script
        run: python consolidated.py
